#服务的名称
spring:
  application:
    name: cloud-gateway
  cloud:
    nacos:
      discovery:
        #注册中心的注册地址
        server-addr: 127.0.0.1:8848
    gateway:
      #设置与服务注册发现组件相结合，这样可以采用服务名的路由策略
      discovery:
        locator:
          enabled: true
      routes:
        #采用自定义路由id
        - id : nacos-consumer
          #采用loadBalanceClient方式请求，以lb://开头，后面的是注册在Nacos上的服务名
          uri: lb://nacos-consumer
          #predicates  主要作用是匹配用户的请求，有很多方法
          predicates:
            - Method=GET,POST


#服务器的运行端口
server:
  port: 9000
