#服务的名称
spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        #注册中心的注册地址
        server-addr: 127.0.0.1:8848
    sentinel:
      enabled: true
#服务器的运行端口
server:
  port: 8082
